env:
  global:
    - secure: DUTI6xnk6emxAGtabSBfFH5QO6jxkRgjCWZp6fnXGrT125ZJ1Gdmf7+O9Gm/qfv9g2zUwjAnptgXUPvPT3xkdB256Ev7eLok9yTwErRd4vubbmxxu7+EqavYg1kQtdb6UStZ5c1Yz/S2mlqOxG5KMQxom80WU9Cfdq096q8hfeJ25hsNdoKBs1EN4Dyb8VxDdTRBHbADE8prqEDtNEprLEYBKzNkH9EbvR/1sPpZ6tsWFKG5mLNifaV/BDfogoFhsgex5EAibpUhXgC4L9zsJMk0Xh8iUOXNkxp7dsOxMeazEtfnUxB26nXUaH2aSopnahmznEtmsKWxLrUheKVKX8rms5fAWTvC8O7p5KYmijzckWGsLK02xRa2lFd71Muw73ZTHL3fLwRJKF7JuU1Aw9bWcVBVjh6rRVaXJloyvJ5rlqvlCWLbUmAJp3QeBJC8MYDenT2G0RIfGEAitNI91IleJrRkX9jmgdzTwa0q+37imIk/H0F4joG4RxXYIx/OU7a95cYvR2pZ9I7jmaRYMlK9jR9huykoP4J2HdsKvkIZhvaIc/wh37B2Pe+tm42vZtcpu3Axym078T5oBs2NDrBYKX0QEpG+eFNA7nshpcPkKvSh2BJN/GFEPgbuSbuzFPYUTmhGOEsM7g1vIsds+rb3zs5/wf48tTiBhPBYh00=
    - secure: fPlYvh+ezjSZKwXY2vef4QNecF7oB2CN0LsLez9ufWUolk/bBtI5lVVE7ACt+7zJumCVA9sQOwhf4RS42626elpfpOWD5TIl4yMMoG9/B7ABtx2bsD5+L2ztW8+WvBjT9weTZUk5XC63VJy/oTsvhB38xprCVypm/DT/sDV3z1MaP5WSsXLymNgbVxhbdiPwZ+c/boHnVnx+kPLyvvr2+9YPB8cXAXJKOs9O77+HsFKLZqx+ra1tM7gqD7AY5oW5WTHUwFM0ccXd8/uCi+qWSsFqUUQlbv7wAIlto8Bnq6DVd7x6bc915Tz8FKfakXuMbEjQ47Kq+Wr4QgUMhybtcE5lwCzxTs5vz/6OkeIWSvSAFyXOHCA2/7rjNrIgT10SEL1TbRNLozKB3SjnTr/vMmPENqh/ZjuEcPte/Eb0rJrw0OfTu3ft/qttTF9Dimk5jBkgqGI2SFSNWq0MhH+flK69Q+ZJsVdfcqJl8PzU3wk/G58SXZYCsVW0i7CsxctRB18+0MUMsGvDIEDZVMIzdfCLXaniwrD8cRaRrVzrbTsxVVQHY3kUELYarA3H33rDev85jTma9My+Ny+YiqXkSvuxRlhJnYbPDFf7Tg/dyDbGyolxWWlP9N8lHO/eZBP9iUoseBJUcz7O46f4beyMTEE1CeGWT48LlpyJ+iQTKK0=

language: objective-c
osx_image: xcode8

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - bundle install
  - carthage bootstrap --platform iOS

branches:
  only:
    - develop
    - master

script:
  - set -o pipefail
  - xcodebuild clean build test -scheme Transport-ios -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' | tee >build.log >(xcpretty -s)
  - bundle exec danger

after_failure:
  - tail -n 500 build.log
