env:
  global:
    secure: DUTI6xnk6emxAGtabSBfFH5QO6jxkRgjCWZp6fnXGrT125ZJ1Gdmf7+O9Gm/qfv9g2zUwjAnptgXUPvPT3xkdB256Ev7eLok9yTwErRd4vubbmxxu7+EqavYg1kQtdb6UStZ5c1Yz/S2mlqOxG5KMQxom80WU9Cfdq096q8hfeJ25hsNdoKBs1EN4Dyb8VxDdTRBHbADE8prqEDtNEprLEYBKzNkH9EbvR/1sPpZ6tsWFKG5mLNifaV/BDfogoFhsgex5EAibpUhXgC4L9zsJMk0Xh8iUOXNkxp7dsOxMeazEtfnUxB26nXUaH2aSopnahmznEtmsKWxLrUheKVKX8rms5fAWTvC8O7p5KYmijzckWGsLK02xRa2lFd71Muw73ZTHL3fLwRJKF7JuU1Aw9bWcVBVjh6rRVaXJloyvJ5rlqvlCWLbUmAJp3QeBJC8MYDenT2G0RIfGEAitNI91IleJrRkX9jmgdzTwa0q+37imIk/H0F4joG4RxXYIx/OU7a95cYvR2pZ9I7jmaRYMlK9jR9huykoP4J2HdsKvkIZhvaIc/wh37B2Pe+tm42vZtcpu3Axym078T5oBs2NDrBYKX0QEpG+eFNA7nshpcPkKvSh2BJN/GFEPgbuSbuzFPYUTmhGOEsM7g1vIsds+rb3zs5/wf48tTiBhPBYh00=

language: objective-c
osx_image: xcode7.3

install:
  - carthage bootstrap --platform iOS

branches:
   only:
     - develop
     - master
    

script:
  - set -o pipefail
  - xcodebuild clean build test -scheme Transport-ios -destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' | xcpretty -s
