name: Xcode 13 iOS 15 Simulator Test

on: 
  workflow_dispatch:
jobs:
  Run_Tests_Xcode_13_0_iOS_15_0:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app && /usr/bin/xcodebuild -version
      
    - name: Carthage
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: carthage bootstrap --platform ios --use-xcframeworks

    - name: Run tests
      run: xcodebuild test -scheme WireTransport -project WireTransport.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 8,OS=15.0' | xcpretty && exit ${PIPESTATUS[0]}
